//This is for running the REST Client for testing purposes
//just click on the Send Request below

//LocalHost
### Get all contacts
GET http://localhost:8080/characters

### Get contact by ID
GET http://localhost:8080/characters/65aaae4b0ff1a59c000cfe63

### Get contact by ID
GET http://localhost:8080/characters/65aaaef90ff1a59c000cfe64

### Get contact by ID
GET http://localhost:8080/characters/65aab0110ff1a59c000cfe65

### Get contact by ID
GET http://localhost:8080/characters/65ab15dcc1f33a000b6d1d2a

### Create contact
POST http://localhost:8080/characters HTTP/1.1
content-type: application/json

{
     "firstName":"Catherine",
    "lastName":"Muller",
    "email":"cmuller@mail.com",
    "favoriteColor":"red",
    "birthday":"01/18/1936"
}

### PUT (update) contact (works)
PUT http://localhost:8080/characters/65b5c36bc842fca4f72c9f29 HTTP/1.1
content-type: application/json

{
    "firstName":"Jacob",
    "lastName":"Muller",
    "email":"test3@mail.com",
    "favoriteColor":"orange",
    "birthday":"05/27/93"
}
### DELETE contact delete Jeremiah
DELETE http://localhost:8080/characters/65b5c5b8c842fca4f72c9f2b HTTP/1.1 

### Create contact (works) 
POST http://localhost:8080/characters HTTP/1.1
content-type: application/json

{
    "firstName":"Winter",
    "lastName":"Muller",
    "email":"wmuller@mail.com",
    "favoriteColor":"black",
    "birthday":"09/04/2014"
}

### PUT contact (works)
PUT http://localhost:8080/characters/65b5c443c842fca4f72c9f2a HTTP/1.1
content-type: application/json

{
    "firstName":"Nathan",
    "lastName":"Muller",
    "email":"test4@mail.com",
    "favoriteColor":"chocolate",
    "birthday":"10/15/97"
}


### DELETE contact
DELETE http://localhost:8080/characters/65b5d8af9b3f581f8499e701 HTTP/1.1


