//This is for running the REST Client for testing purposes
//just click on the Send Request below

//LocalHost
### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID
GET http://localhost:8080/contacts/65aaae4b0ff1a59c000cfe63

### Get contact by ID
GET http://localhost:8080/contacts/65aaaef90ff1a59c000cfe64

### Get contact by ID
GET http://localhost:8080/contacts/65aab0110ff1a59c000cfe65

### Get contact by ID
GET http://localhost:8080/contacts/65ab15dcc1f33a000b6d1d2a

### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Isabel",
    "lastName":"Muller",
    "email":"iMuller@test.com",
    "favoriteColor":"Brown",
    "birthday":"11/19/1998"
}

### PUT (update) contact (works)
PUT http://localhost:8080/contacts/65aaaef90ff1a59c000cfe64 HTTP/1.1
content-type: application/json

{
    "firstName":"Jacob",
    "lastName":"Muller",
    "email":"test3@mail.com",
    "favoriteColor":"blue",
    "birthday":"05/27/93"
}
### DELETE contact delete Melinda
DELETE http://localhost:8080/contacts/65aaae4b0ff1a59c000cfe63 HTTP/1.1 

### Create contact (works) add Josiah
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Josiah",
    "lastName":"Muller",
    "email":"jMuller@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/30/1927"
}

### PUT contact (works)
PUT http://localhost:8080/contacts/65aab0110ff1a59c000cfe65 HTTP/1.1
content-type: application/json

{
    "firstName":"Nathan",
    "lastName":"Muller",
    "email":"test4@mail.com",
    "favoriteColor":"teal",
    "birthday":"10/15/97"
}


### DELETE contact (Josiah)
DELETE http://localhost:8080/contacts/65aab0110ff1a59c000cfe64 HTTP/1.1

### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"John",
    "lastName":"Muller",
    "email":"muller02@test.com",
    "favoriteColor":"green",
    "birthday":"11/11/1963"
}

